#!/bin/sh
usage() {
	echo "usage: bump-version <version-id>"
}

if [ $# -ne 1 ]; then
	usage
	exit 1
fi

if ! sed 's/^gittheflow_VERSION=.*$/gittheflow_VERSION='$1'/g' git-theflow-version > .git-theflow-version.new; then
	echo "Could not replace gittheflow_VERSION variable." >&2
	exit 2
fi

mv .git-theflow-version.new git-theflow-version
git add git-theflow-version
git commit -m "Bumped version number to $1" git-theflow-version
